---
abstract: 'Determine MIME types of data or files using libmagic'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.28'
  Test::More: '0.94'
  base: '0'
  perl: '5.010'
configure_requires:
  FFI::CheckLib: '0'
  Module::Build: '0.28'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-LibMagic-FFI
requires:
  FFI::CheckLib: '0'
  FFI::Raw: '0'
  FFI::Util: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/plicease/File-LibMagic-FFI/issues
  homepage: http://perl.wdlabs.com/File-LibMagic-FFI
  repository: git://github.com/plicease/File-LibMagic-FFI.git
version: '0.02'
